OCPBUGS-32844: bump go-jose to fix CVE-2024-28180
openshift/builder pull request #398
Opened 2024-06-19 12:13 UTC by avinal

## Changes

- Bump gopkg.in/go-jose/go-jose.v2 to 2.6.3

Signed-off-by: Avinal Kumar <avinal@redhat.com>

2024-06-19 12:18 UTC, avinal commented
/jira-refresh

2024-06-24 08:27 UTC, avinal commented
/retest

2024-06-24 12:14 UTC, adambkaplan requested changes

2024-06-24 12:14 UTC, adambkaplan commented on go.mod
> +	github.com/containers/buildah v1.33.8
/hold

We can't do this in 4.14 without the same code existing in 4.15. Otherwise customers will downgrade buildah whenthey upgrade OCP.

2024-06-26 08:41 UTC, avinal commented
/retest

2024-06-26 20:34 UTC, adambkaplan commented
Is this blocked by https://github.com/openshift/origin/pull/28904 and its cherry-picks?

2024-07-09 12:30 UTC, adambkaplan commented
/jira refresh

2024-08-06 12:48 UTC, avinal commented
/retest

2024-10-29 11:07 UTC, sayan-biswas commented
/test e2e-aws-ovn-builds-techpreview
/test e2e-aws-ovn-builds

2024-10-29 11:40 UTC, sayan-biswas approved these changes

2025-03-30 00:01 UTC, closed without merging