OCPBUGS-45321 : skipping some unit tests to avoid failures as they are duplicate
openshift/builder pull request #412
Opened 2024-12-04 07:01 UTC by prabhapa

Recent git upgrade to fix a CVE is causing some issues lately for the unit tests. The git upgrade disabled file protocol by default which is causing the problem.Those tests are skipped as they are duplicate.

2024-12-04 07:33 UTC, prabhapa commented
/jira refresh

2024-12-06 14:42 UTC, adambkaplan requested changes
In addition to the updated skip message, please use a well-formatted and _specific_ git commit message.

I love referencing the Tekton community standards, because they do an excellent job of explaining what a good commit message is: https://github.com/tektoncd/community/blob/main/standards.md#commit-messages

2024-12-06 14:42 UTC, adambkaplan commented on pkg/build/builder/source_test.go
> +	t.Skip("This test as its failing permanently due to Git upgrade after a CVE.Similar tests happen on other places hence skipping it")
Be specific, and reference JIRA or other identifiers where appropriate. Ditto for the other comments.

```suggestion
	t.Skip("OCPBUGS-45321: git file:// protocol no longer allowed by default. See CVE-2022-39253")
```

2024-12-06 14:43 UTC, adambkaplan commented
/approve

Acceptable to skip the unit tests due to change in git's behavior. We have plenty of git test coverage via the end to end tests in openshift/origin.

2024-12-06 14:53 UTC, adambkaplan commented
/override ci/prow/e2e-aws-ovn-builds

Known issue with builds e2e test

2024-12-09 15:54 UTC, adambkaplan commented
Please squash commits, then I can add LGTM

2024-12-11 05:25 UTC, sayan-biswas approved these changes

2024-12-11 05:37 UTC, sayan-biswas commented
/lgtm

2024-12-11 05:51 UTC, prabhapa commented
/docs-approved

2024-12-11 05:51 UTC, prabhapa commented
qe-approved

2024-12-11 05:51 UTC, prabhapa commented
/qe-approved

2024-12-11 05:52 UTC, prabhapa commented
/px-approved

2024-12-12 07:52 UTC, sayan-biswas commented
@prabhapa I don't think that syntax works for labels also.

/label px-approved
/label docs-approved
/label qe-approved

2024-12-12 11:28 UTC, sayan-biswas commented
/override "ci/prow/e2e-aws-ovn-builds"

2024-12-12 11:32 UTC, merged

2024-12-16 11:17 UTC, prabhapa commented
/cherry-pick release-4.18

2024-12-31 09:28 UTC, prabhapa commented
/cherry-pick release-4.17 release 4.16

2024-12-31 10:17 UTC, prabhapa commented
/jira refresh